name: Workflow for Environment Files
  
on: 
  workflow_dispatch
  
permissions:  
  checks: write   # Allows posting test summaries and check-runs
  contents: read  # Required for repo access
  
jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11"] # "3.8", "3.9", "3.10",
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=scripts  --cov-report=term --cov-report=xml > coverage.txt  2>&1 || true

      - name: Display coverage report in GitHub Summary
        run: |
          echo "${{ github.ref_name }} __ skip-uem-and-cp-artifacts-promotion: ${{ startsWith(github.ref_name, 'lrb') ? 'true' : 'false' }}" 
          echo "### Code Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY


      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run tests and save results
        run: pytest --junitxml=test-results.xml 2>&1 || true
        
      - name: NUnit Test Result
        uses: EnricoMi/publish-unit-test-result-action@v2
        continue-on-error: true
        if: always()
        with:
          check_name: "Build Application Unit Test Results"
          check_run: true
          action_fail: true
          fail_on: "test failures"
          files: "test-results.xml"
          action_fail_on_inconclusive: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
