name: Workflow for Environment Files

  
on: 
  workflow_dispatch

env:
  BAMBOO_BUILDNUMBER: '${{ github.workflow }}-${{ github.job }}-${{ github.run_id }}'
  REF: "${{ github.ref }}"
  TARGET_BRANCH: ${REF#refs/heads/}
  BALANCE: 35
  COLOR: "Blue"
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  BAMBOO_KEY: "${{ vars.BUILD_KEY || format('{0}-{1}-{2}', github.workflow, github.job, github.run_id) }}"
  
jobs:
  job1a:
    runs-on: windows-latest
    steps:
      - name: Set powershell
        id: set-powershell
        env:
          g.workspace: ${{ github.workspace }}
          g_workspace: $env:GITHUB_WORKSPACE
        run: |
          Install-Module -Name Invoke-MsBuild -Force
          Import-Module Invoke-MsBuild
          $file_path = "BambooBuild.proj"
          Invoke-MsBuild -Path $file_path -MsBuildParameters "/p:Configuration=Release /m /nr:false /verbosity:diagnostic /fl -v:diag"
